---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "plugin-health-scoring.fullname" . }}
  labels:
{{ include "plugin-health-scoring.labels" . | indent 4 }}
type: Opaque
data:
  databasePassword: {{ .Values.database.password | b64enc }}
  githubOauthToken: {{ .Values.config.githubOauth | b64enc }}
